config/routes.rb
Rails.application.routes.draw do
  
  resources :games do
    resources :comments
  end

  patch 'game/:id/comments/:comment_id/rank_down' => 'comments#rank_down', :as => 'rank_down'
  patch 'game/:id/comments/:comment_id/rank_up' => 'comments#rank_up', :as => 'rank_up'

  root 'games#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :game
  default_scope { order({rank: :desc}, created_at: :desc) }
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.order(rank: :desc)
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @game = Game.find(params[:game_id])
    @comment = @game.comments.create(comment_params)
    redirect_to game_path(@game)
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def rank_up
    @game = Game.find(params[:id])
    @comment = Comment.find(params[:comment_id])
    @comment[:rank] += 1
    respond_to do |format|
      if @comment.update_attributes(rank: @comment[:rank])
        format.html { redirect_to game_path(@game), notice: 'Comment rank was successfully updated.' }
      end
    end
  end

  def rank_down
    @game = Game.find(params[:id])
    @comment = Comment.find(params[:comment_id])
    @comment[:rank] -= 1
    respond_to do |format|
      if @comment.update_attributes(rank: @comment[:rank])
        format.html { redirect_to game_path(@game), notice: 'Comment rank was successfully updated.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :body, :game_id, :comment_time, :rank, :team)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
    @comments = Comment.where(game_id: params[:id]).order(:rank)
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:schedule, :team_1, :team_2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Body</th>
      <th>Game</th>
      <th>Comment time</th>
      <th>Rank</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.body %></td>
        <td><%= comment.game %></td>
        <td><%= comment.comment_time %></td>
        <td><%= comment.rank %></td>
        <td><%= comment.team %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Game:</strong>
  <%= @comment.game %>
</p>

<p>
  <strong>Comment time:</strong>
  <%= @comment.comment_time %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @comment.rank %>
</p>

<p>
  <strong>Team:</strong>
  <%= @comment.team %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.datetime_select :schedule %>
  </div>
  <div class="field">
    <%= f.label :team_1 %><br>
    <%= f.text_field :team_1 %>
  </div>
  <div class="field">
    <%= f.label :team_2 %><br>
    <%= f.text_field :team_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Back', @game %>

app/views/games/index.html.erb
<h1>Game Listing</h1>

<table>
  <thead>
    <tr>
      <th>Schedule</th>
      <th>Team 1</th>
      <th>Team 2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.schedule.localtime %></td>
        <td><%= game.team_1 %></td>
        <td><%= game.team_2 %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/games/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Schedule:</strong>
  <%= @game.schedule.localtime %>
</p>

<p>
  <strong>Team 1:</strong>
  <%= @game.team_1 %>
</p>

<p>
  <strong>Team 2:</strong>
  <%= @game.team_2 %>
</p>

<strong>Add a comment:</strong>
<%= form_for([@game, @game.comments.build]) do |f| %>
 <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.select :team, options_for_select([@game.team_1, @game.team_2]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p>
  <strong>Comments:</strong><br>
  <% @comments.each do |comment| %>
    <%= comment.author %> | Team: <%= comment.team %> |
    <%= link_to image_tag('arrow_down.png', {id: "rank_down", class: "arrow"}), rank_down_path(@game, comment), method: :patch %> <%= comment.rank %> <%= link_to image_tag('arrow_up.png', {id: "rank_up", class: "arrow"}), rank_up_path(@game, comment), method: :patch %>
    <p><%= comment.created_at.localtime %></p>
    <p><%= comment.body %></p>
    <p>=============================================</p>
  <% end %>
</p>



<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', root_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameChat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>